"""Synthetic Joint Multi-Agent Scenario Generator.

[SYNTHETIC DATA SOURCE NOTICE]
==============================
WARNING: ALL DATA GENERATED BY THIS MODULE IS SYNTHETIC TEST HARNESS DATA.
This module constructs paired test scenarios combining synthetic Windows Host
endpoint telemetry and IAM authentication logs. It does NOT represent real
enterprise telemetry, EDR events, or production authentication logs.
This synthetic test harness exists specifically to exercise cross-agent entity
correlation, multi-source conflict resolution, and joint escalation logic
in downstream coordinator modules (e.g., Module 13b conflict resolver).

Paired scenarios link Host and IAM events via a shared endpoint entity:
- 'computer' in Host events matches 'target_computer' in IAM events.
- Scenarios cover all four combinations (BOTH_BENIGN, HOST_ATTACK_ONLY,
  IAM_ATTACK_ONLY, BOTH_ATTACK) drawn from a constrained pool of ~20 computers.
"""

from collections import Counter
from pathlib import Path
import sys
from typing import Any, Dict, List
import numpy as np
import pandas as pd

# Ensure project root is available for imports
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from modules.host_dataset_generator import (
    ATTACK_PROCESS_PAIRS,
    BENIGN_PROCESS_PAIRS,
    FAKE_USERS,
    INJECTION_PROCESS_PAIRS,
    INJECTION_VARIED_PAIRS,
    PRIV_ESC_PROCESS_PAIRS,
    PRIV_ESC_VARIED_PAIRS,
)
from modules.iam_dataset_generator import (
    AUTH_RESULTS,
    AUTH_TYPES,
    LOGON_TYPES,
)

# Constrained pool of 20 fake computers to ensure realistic cross-scenario entity overlap
SCENARIO_COMPUTERS: List[str] = [f"PC-{i:04d}" for i in range(1, 21)]

# Scenario combination categories
SCENARIO_TYPES: List[str] = [
    "BOTH_BENIGN",
    "HOST_ATTACK_ONLY",
    "IAM_ATTACK_ONLY",
    "BOTH_ATTACK",
]


def _generate_host_event(
    event_id: int,
    computer: str,
    user: str,
    timestamp: str,
    is_attack: bool,
    rng: np.random.Generator,
) -> Dict[str, Any]:
    """Generates a single synthetic host event adhering to host_dataset_generator schema."""
    if not is_attack:
        # Benign: ~15% controlled overlap with attack-associated pairs
        if rng.random() < 0.15:
            pair = ATTACK_PROCESS_PAIRS[rng.integers(0, len(ATTACK_PROCESS_PAIRS))]
        else:
            pair = BENIGN_PROCESS_PAIRS[rng.integers(0, len(BENIGN_PROCESS_PAIRS))]

        return {
            "event_id": event_id,
            "timestamp": timestamp,
            "computer": computer,
            "user": user,
            "process_name": pair[1],
            "parent_process": pair[0],
            "is_malicious": 0,
            "label": "BENIGN",
        }
    else:
        # Attack: 50% Injection, 50% Privilege Escalation
        if rng.random() < 0.5:
            label = "SUSPICIOUS_PROCESS_INJECTION"
            if rng.random() < 0.10:
                pair = INJECTION_VARIED_PAIRS[rng.integers(0, len(INJECTION_VARIED_PAIRS))]
            else:
                pair = INJECTION_PROCESS_PAIRS[rng.integers(0, len(INJECTION_PROCESS_PAIRS))]
        else:
            label = "PRIVILEGE_ESCALATION_ATTEMPT"
            if rng.random() < 0.10:
                pair = PRIV_ESC_VARIED_PAIRS[rng.integers(0, len(PRIV_ESC_VARIED_PAIRS))]
            else:
                pair = PRIV_ESC_PROCESS_PAIRS[rng.integers(0, len(PRIV_ESC_PROCESS_PAIRS))]

        return {
            "event_id": event_id,
            "timestamp": timestamp,
            "computer": computer,
            "user": user,
            "process_name": pair[1],
            "parent_process": pair[0],
            "is_malicious": 1,
            "label": label,
        }


def _generate_iam_event(
    event_id: int,
    target_computer: str,
    source_computer: str,
    user: str,
    timestamp: str,
    is_attack: bool,
    rng: np.random.Generator,
) -> Dict[str, Any]:
    """Generates a single synthetic IAM event adhering to iam_dataset_generator schema."""
    if not is_attack:
        # Benign distributions
        auth_result = rng.choice(AUTH_RESULTS, p=[0.95, 0.05])
        logon_type = rng.choice(LOGON_TYPES, p=[0.45, 0.45, 0.04, 0.03, 0.03])
        auth_type = rng.choice(AUTH_TYPES, p=[0.48, 0.48, 0.04])
        label = "BENIGN"
        is_malicious = 0
    else:
        # Attack: 50% Brute Force, 50% Pass-the-Hash
        is_malicious = 1
        if rng.random() < 0.5:
            label = "BRUTE_FORCE_LOGIN"
            auth_result = rng.choice(AUTH_RESULTS, p=[0.10, 0.90])
            logon_type = rng.choice(LOGON_TYPES, p=[0.02, 0.92, 0.01, 0.01, 0.04])
            auth_type = rng.choice(AUTH_TYPES, p=[0.10, 0.85, 0.05])
        else:
            label = "PASS_THE_HASH"
            auth_result = rng.choice(AUTH_RESULTS, p=[0.85, 0.15])
            logon_type = rng.choice(LOGON_TYPES, p=[0.02, 0.55, 0.01, 0.01, 0.41])
            auth_type = rng.choice(AUTH_TYPES, p=[0.01, 0.98, 0.01])

    return {
        "event_id": event_id,
        "timestamp": timestamp,
        "source_computer": source_computer,
        "target_computer": target_computer,
        "user": user,
        "auth_type": str(auth_type),
        "logon_type": str(logon_type),
        "auth_result": str(auth_result),
        "is_malicious": is_malicious,
        "label": label,
    }


def generate_joint_scenarios(
    n_scenarios: int = 200,
    random_state: int = 42,
) -> List[Dict[str, Any]]:
    """Generates paired Host and IAM test scenarios sharing a common target computer.

    [SYNTHETIC TEST HARNESS NOTICE]
    All scenarios are synthetically constructed to benchmark multi-agent correlation
    and conflict resolution. They do NOT represent real endpoint telemetry.

    Parameters
    ----------
    n_scenarios : int, default=200
        Total number of paired joint scenarios to generate.
    random_state : int, default=42
        Random seed for reproducibility.

    Returns
    -------
    List[Dict[str, Any]]
        List of scenario dictionaries containing:
        - scenario_id: int (1 to n_scenarios)
        - computer: str (shared hostname, e.g. "PC-0007")
        - host_event: dict (Host telemetry event)
        - iam_event: dict (IAM telemetry event with target_computer == computer)
        - scenario_type: str ("BOTH_BENIGN", "HOST_ATTACK_ONLY", "IAM_ATTACK_ONLY", "BOTH_ATTACK")
    """
    rng = np.random.default_rng(random_state)

    # 1. Distribute scenario types roughly evenly across n_scenarios
    base_counts = n_scenarios // len(SCENARIO_TYPES)
    remainder = n_scenarios % len(SCENARIO_TYPES)
    type_assignments = SCENARIO_TYPES * base_counts + SCENARIO_TYPES[:remainder]
    rng.shuffle(type_assignments)

    # 2. Time progression simulation over 24 hours
    base_time = pd.Timestamp("2025-01-15 08:00:00")
    second_offsets = np.sort(rng.uniform(0, 86400, size=n_scenarios))

    scenarios: List[Dict[str, Any]] = []

    for i in range(n_scenarios):
        scenario_id = i + 1
        stype = type_assignments[i]

        # Shared computer entity selected from fixed pool of 20 machines
        shared_computer = str(rng.choice(SCENARIO_COMPUTERS))
        source_computer = str(rng.choice(SCENARIO_COMPUTERS))
        user = str(rng.choice(FAKE_USERS))

        # Correlated timestamps: Host and IAM events occur close in time (within +/- 30s)
        scenario_time = base_time + pd.to_timedelta(second_offsets[i], unit="s")
        host_timestamp = scenario_time.strftime("%Y-%m-%d %H:%M:%S")
        iam_delta_sec = float(rng.uniform(-30, 30))
        iam_timestamp = (scenario_time + pd.to_timedelta(iam_delta_sec, unit="s")).strftime(
            "%Y-%m-%d %H:%M:%S"
        )

        host_is_attack = stype in ("HOST_ATTACK_ONLY", "BOTH_ATTACK")
        iam_is_attack = stype in ("IAM_ATTACK_ONLY", "BOTH_ATTACK")

        host_ev = _generate_host_event(
            event_id=scenario_id,
            computer=shared_computer,
            user=user,
            timestamp=host_timestamp,
            is_attack=host_is_attack,
            rng=rng,
        )

        iam_ev = _generate_iam_event(
            event_id=scenario_id,
            target_computer=shared_computer,
            source_computer=source_computer,
            user=user,
            timestamp=iam_timestamp,
            is_attack=iam_is_attack,
            rng=rng,
        )

        scenarios.append(
            {
                "scenario_id": scenario_id,
                "computer": shared_computer,
                "host_event": host_ev,
                "iam_event": iam_ev,
                "scenario_type": stype,
            }
        )

    return scenarios


if __name__ == "__main__":
    print("=" * 86)
    print("SYNTHETIC JOINT MULTI-AGENT SCENARIO GENERATOR")
    print("[SYNTHETIC DATA NOTICE]: Constructed test harness for cross-agent conflict resolution.")
    print("=" * 86)

    scenarios = generate_joint_scenarios(n_scenarios=200, random_state=42)

    # 1. Print scenario type counts
    type_counts = Counter(s["scenario_type"] for s in scenarios)
    print(f"\nGenerated {len(scenarios)} joint scenarios across 20 shared computers.")
    print("\nScenario Type Distribution:")
    for stype in SCENARIO_TYPES:
        print(f"  {stype:<20}: {type_counts.get(stype, 0):>4}")

    # 2. Print 2 example scenarios from "BOTH_ATTACK" side by side
    both_attacks = [s for s in scenarios if s["scenario_type"] == "BOTH_ATTACK"]

    print("\n" + "=" * 86)
    print("SIDE-BY-SIDE EXAMPLES: 'BOTH_ATTACK' SCENARIOS (Correlated Multi-Stage Intrusions)")
    print("=" * 86)

    for idx, sc in enumerate(both_attacks[:2], start=1):
        h = sc["host_event"]
        m = sc["iam_event"]
        print(f"\n[Example {idx}]: Scenario #{sc['scenario_id']} | Shared Computer: {sc['computer']} | Type: {sc['scenario_type']}")
        print("-" * 86)
        print(f"  {'HOST EVENT TELEMETRY':<40} | {'IAM AUTHENTICATION TELEMETRY':<40}")
        print(f"  {'-'*38:<40} | {'-'*38:<40}")
        print(f"  {'Event ID':<16}: {h['event_id']:<22} | {'Event ID':<18}: {m['event_id']}")
        print(f"  {'Timestamp':<16}: {h['timestamp']:<22} | {'Timestamp':<18}: {m['timestamp']}")
        print(f"  {'Computer':<16}: {h['computer']:<22} | {'Target Computer':<18}: {m['target_computer']}")
        print(f"  {'User':<16}: {h['user']:<22} | {'Source Computer':<18}: {m['source_computer']}")
        print(f"  {'Process':<16}: {h['process_name']:<22} | {'User':<18}: {m['user']}")
        print(f"  {'Parent Process':<16}: {h['parent_process']:<22} | {'Auth Type':<18}: {m['auth_type']}")
        print(f"  {'Label':<16}: {h['label']:<22} | {'Logon Type':<18}: {m['logon_type']}")
        print(f"  {'Is Malicious':<16}: {h['is_malicious']:<22} | {'Auth Result':<18}: {m['auth_result']}")
        print(f"  {'':<16}  {'':<22} | {'Label':<18}: {m['label']}")
        print("-" * 86)

    # 3. Aggregate Ground-Truth Verification (IAM Attack Auth Results across all 200 scenarios)
    print("\n" + "=" * 86)
    print("AGGREGATE IAM AUTH_RESULT VALIDATION ACROSS ALL SCENARIOS")
    print("=" * 86)

    iam_events_all = [s["iam_event"] for s in scenarios]
    pth_events = [e for e in iam_events_all if e["label"] == "PASS_THE_HASH"]
    brute_events = [e for e in iam_events_all if e["label"] == "BRUTE_FORCE_LOGIN"]

    pth_counts = Counter(e["auth_result"] for e in pth_events)
    brute_counts = Counter(e["auth_result"] for e in brute_events)

    pth_total = len(pth_events)
    pth_success = pth_counts.get("SUCCESS", 0)
    pth_failure = pth_counts.get("FAILURE", 0)
    pth_success_pct = (pth_success / pth_total * 100.0) if pth_total > 0 else 0.0
    pth_failure_pct = (pth_failure / pth_total * 100.0) if pth_total > 0 else 0.0

    brute_total = len(brute_events)
    brute_success = brute_counts.get("SUCCESS", 0)
    brute_failure = brute_counts.get("FAILURE", 0)
    brute_success_pct = (brute_success / brute_total * 100.0) if brute_total > 0 else 0.0
    brute_failure_pct = (brute_failure / brute_total * 100.0) if brute_total > 0 else 0.0

    print(f"\n[PASS_THE_HASH] (Total: {pth_total} events, Expected Target: ~85% SUCCESS / ~15% FAILURE)")
    print(f"  SUCCESS : {pth_success:>3}/{pth_total} ({pth_success_pct:>5.1f}%)")
    print(f"  FAILURE : {pth_failure:>3}/{pth_total} ({pth_failure_pct:>5.1f}%)")

    print(f"\n[BRUTE_FORCE_LOGIN] (Total: {brute_total} events, Expected Target: ~10% SUCCESS / ~90% FAILURE)")
    print(f"  SUCCESS : {brute_success:>3}/{brute_total} ({brute_success_pct:>5.1f}%)")
    print(f"  FAILURE : {brute_failure:>3}/{brute_total} ({brute_failure_pct:>5.1f}%)")
    print("=" * 86)
